//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchool.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int id { get; set; }
        public int idDepartment { get; set; }
        public int idUser { get; set; }
        public int idTeacher { get; set; }
        public int idStatus { get; set; }
        public System.DateTime dateLesson { get; set; }
        public int numberOfHours { get; set; }
        public decimal cost { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual StatusLesson StatusLesson { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual User User { get; set; }
    }
}
